### PR TITLE
Created Test and View for IncidentLog list

### PR DESCRIPTION
**Pull request by jiaqi1993**
**Why**
Created Test and View for Incident Log to List all incident logs, combined test in the postman test file.

### CODE REVIEW

**Review by melvynsngg — COMMENTED** [review]
Im thinking sorting by incident would be valuable. Compared to just taking everything, PMO wont know which log is for which event?

**Comment by jiaqi1993** [comment]
hmm, if that's the case may i know if there's a need in CMS status to pass me the list of incident ids?

**Comment by jiaqi1993** [comment]
Another way of implementation of this is to keep tracking of the activation time for CMSStatus, so I can print out all incident that activated after this start timing. (Compare with incident activation time)

**Comment by chinjieh** [comment]
Erm sorry for not following this PR, but why do we need a view to `list` IncidentLogs? I thought generating PMO emails is through the backend.

If it's for the email to PMO, then why not just use make a django query on the `IncidentLog` model (see [QuerySet APIs](https://docs.djangoproject.com/en/1.10/ref/models/querysets/#queryset-api) for all possible queries like **order_by** in the example below):

```
incident_logs = IncidentLog.objects.order_by('incident_id').order_by('datetime').all()
# other processing
# then iterate incident_logs and write to text
```

There might be a better way to do it, so you can take a look at the QuerySet APIs.

A view to `list` IncidentLogs is good however, but it's not relevant to generating PMO emails. Unless I'm missing something here... (don't delete your view because it can be used for other things!!)

**Comment by jiaqi1993** [comment]
The view is only created for the testing purpose to see all objects in Incidents Log, for the email sending part it's using a reversed loop to retrieve the latest update 1st then to the oldest. You may login to the email to see the output. All logs with the same id will be grouped together. If everything's okay then I will have to PR and commit to test the scheduler on server side.

**Comment by chinjieh** [comment]
> The view is only created for the testing purpose to see all objects in Incidents Log, for the email sending part it's using a reversed loop to retrieve the latest update 1st then to the oldest. You may login to the email to see the output. All logs with the same id will be grouped together.

Oh ok that makes sense.

**Pull request merged**
