### PR TITLE
Update test for Agency

### PR DESCRIPTION
**Pull request by jiaqi1993**
**Why**
Update the test for Agency

### CODE REVIEW

**Review by chinjieh — APPROVED** [review]
Looks good to me, can merge

**Review by chinjieh — COMMENTED** [review]
Oh sorry, didn't see that the tests are in a different file. Since the outcome is the same it shouldn't matter, but it'll definitely be better if its in the same file for consistency

**Comment by jiaqi1993** [comment]
Noted, will compile it together with the original file after i’m done with the IncidentCallReport Test.

Thanks.

**Comment by chinjieh** [comment]
Okay, you can merge it in then! :)

**Pull request merged**
